import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#211018',
  },
  app: {
    flex: 1,
    backgroundColor: '#301a22',
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: '#fff2e9',
    fontSize: 20,
    fontWeight: '900',
  },
  headerSub: {
    color: 'rgba(255,240,237,0.66)',
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  refreshButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshText: {
    color: '#fff2e9',
    fontSize: 25,
  },
  searchBox: {
    marginHorizontal: 18,
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,240,237,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 15,
    paddingRight: 0,
  },
  searchIcon: {
    color: 'rgba(255,240,237,0.72)',
    fontSize: 18,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#fff2e9',
    fontSize: 13,
    fontWeight: '900',
    paddingVertical: 10,
  },
  searchSubmit: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a8a',
  },
  searchSubmitDisabled: {
    opacity: 0.5,
  },
  searchSubmitText: {
    color: '#301a22',
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 26,
  },
  searchSuggestionList: {
    gap: 7,
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 2,
  },
  searchSuggestionChip: {
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,240,237,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
  },
  searchSuggestionChipDisabled: {
    opacity: 0.55,
  },
  searchSuggestionText: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '900',
  },
  dataStatusBanner: {
    marginHorizontal: 18,
    marginTop: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(255,240,237,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.14)',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dataStatusBannerLoading: {
    borderColor: 'rgba(245,207,118,0.35)',
  },
  dataStatusBannerWarning: {
    backgroundColor: '#3a2024',
    borderColor: 'rgba(246,196,83,0.28)',
  },
  dataStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#f5cf76',
  },
  dataStatusDotLoading: {
    backgroundColor: '#8cc9ff',
  },
  dataStatusContent: {
    flex: 1,
    minWidth: 0,
  },
  dataStatusLabel: {
    color: '#fff2e9',
    fontSize: 12,
    fontWeight: '900',
  },
  dataStatusMessage: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 3,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 132,
  },
  searchResultCard: {
    borderRadius: 22,
    backgroundColor: '#fff7ee',
    padding: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  searchResultMain: {
    flex: 1,
    minWidth: 0,
  },
  searchResultKicker: {
    color: '#8f7f87',
    fontSize: 11,
    fontWeight: '900',
  },
  searchResultTitle: {
    color: '#2f1822',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  searchResultQuery: {
    color: '#6b5a62',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  searchResultChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  searchResultChip: {
    borderRadius: 14,
    backgroundColor: '#eadde3',
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  searchResultChipLabel: {
    color: '#8f7f87',
    fontSize: 10,
    fontWeight: '900',
  },
  searchResultChipValue: {
    color: '#2f1822',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  searchResultNote: {
    borderRadius: 14,
    backgroundColor: '#fffdf7',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginTop: 10,
  },
  searchResultNoteWarning: {
    backgroundColor: '#fff0d1',
  },
  searchResultNoteText: {
    color: '#6b5a62',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  searchResultNoteWarningText: {
    color: '#7a4217',
  },
  searchResultBadge: {
    minWidth: 58,
    minHeight: 38,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginTop: 2,
  },
  searchResultBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  weatherSwitch: {
    gap: 7,
    paddingBottom: 10,
  },
  weatherChip: {
    minWidth: 52,
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,240,237,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  weatherChipText: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '900',
  },
  weatherChipTextActive: {
    color: '#301a22',
  },
  decisionCard: {
    borderRadius: 30,
    padding: 18,
    minHeight: 430,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.18)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
  },
  decisionArtGlow: {
    position: 'absolute',
    width: 270,
    height: 250,
    borderRadius: 135,
    opacity: 0.42,
    top: -92,
    right: -76,
  },
  decisionArtAccent: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: 105,
    opacity: 0.24,
    left: -78,
    bottom: 64,
  },
  decisionHeroArea: {
    minHeight: 236,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 0,
  },
  mockCompass: {
    position: 'relative',
    zIndex: 2,
    width: 250,
    height: 236,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mockCompassAxisVertical: {
    position: 'absolute',
    width: 1,
    height: 230,
    backgroundColor: 'rgba(255,240,237,0.14)',
  },
  mockCompassAxisHorizontal: {
    position: 'absolute',
    width: 230,
    height: 1,
    backgroundColor: 'rgba(255,240,237,0.14)',
  },
  mockRingOne: {
    position: 'absolute',
    width: 232,
    height: 232,
    borderRadius: 116,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.22)',
  },
  mockRingTwo: {
    position: 'absolute',
    width: 174,
    height: 174,
    borderRadius: 87,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(255,240,237,0.22)',
    opacity: 0.9,
  },
  mockRingThree: {
    position: 'absolute',
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 1,
    backgroundColor: 'rgba(255,240,237,0.10)',
  },
  mockNeedle: {
    position: 'absolute',
    width: 18,
    height: 98,
    borderRadius: 9,
    opacity: 0.42,
    transform: [{ rotate: '36deg' }],
  },
  decisionCompassRing: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.14)',
    top: 45,
    right: 16,
  },
  decisionCompassRingMid: {
    position: 'absolute',
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(255,240,237,0.17)',
    top: 78,
    right: 49,
    opacity: 0.9,
  },
  decisionCompassRingSmall: {
    position: 'absolute',
    width: 122,
    height: 122,
    borderRadius: 61,
    borderWidth: 1,
    borderColor: 'rgba(74,163,255,0.36)',
    backgroundColor: 'rgba(74,163,255,0.10)',
    top: 109,
    right: 80,
  },
  decisionNeedle: {
    position: 'absolute',
    top: 119,
    right: 132,
    width: 18,
    height: 100,
    borderRadius: 8,
    opacity: 0.34,
    transform: [{ rotate: '36deg' }],
  },
  weatherArt: {
    position: 'absolute',
    top: 32,
    right: -4,
    width: 132,
    height: 132,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    transform: [{ rotate: '-4deg' }],
  },
  sunHalo: {
    position: 'absolute',
    width: 122,
    height: 122,
    borderRadius: 61,
    borderWidth: 2,
    borderStyle: 'dashed',
    opacity: 0.72,
  },
  sunCore: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ffd36b',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 28,
  },
  cloudBase: {
    position: 'absolute',
    top: 34,
    right: 10,
    width: 112,
    height: 62,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
  },
  cloudPuffLarge: {
    position: 'absolute',
    top: 6,
    right: 46,
    width: 58,
    height: 58,
    borderRadius: 29,
  },
  cloudPuffSmall: {
    position: 'absolute',
    top: 48,
    right: 0,
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  weatherDrops: {
    position: 'absolute',
    top: 104,
    right: 18,
    width: 92,
    height: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    transform: [{ rotate: '-14deg' }],
  },
  rainDrop: {
    width: 8,
    height: 28,
    borderRadius: 5,
    opacity: 0.82,
  },
  rainDropMiddle: {
    marginTop: 8,
  },
  thunderBolt: {
    position: 'absolute',
    top: 82,
    right: 42,
    width: 44,
    height: 82,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '11deg' }],
  },
  thunderBoltTop: {
    position: 'absolute',
    top: 4,
    left: 18,
    width: 18,
    height: 48,
    borderRadius: 8,
    transform: [{ rotate: '28deg' }],
  },
  thunderBoltBottom: {
    position: 'absolute',
    top: 35,
    left: 8,
    width: 18,
    height: 48,
    borderRadius: 8,
    transform: [{ rotate: '28deg' }],
  },
  snowDots: {
    position: 'absolute',
    top: 106,
    right: 18,
    width: 100,
    height: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  snowDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    opacity: 0.9,
  },
  snowDotMiddle: {
    marginTop: 12,
  },
  fogLines: {
    position: 'absolute',
    top: 106,
    right: -2,
    width: 122,
    gap: 12,
  },
  fogLine: {
    height: 5,
    borderRadius: 4,
    opacity: 0.78,
  },
  fogLineShort: {
    width: 86,
    marginLeft: 26,
  },
  decisionMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
  },
  decisionMetaChipPrimary: {
    minHeight: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  decisionMetaChipPrimaryText: {
    fontSize: 11,
    fontWeight: '900',
  },
  decisionMetaChip: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
    backgroundColor: 'rgba(255,240,237,0.07)',
  },
  decisionMetaChipText: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '900',
  },
  decisionMain: {
    marginTop: 242,
    maxWidth: 260,
  },
  heroSummary: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    marginTop: 2,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  decisionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  decisionLabel: {
    color: 'rgba(255,240,237,0.60)',
    fontSize: 12,
    fontWeight: '900',
  },
  decisionCondition: {
    color: '#fff2e9',
    fontSize: 12,
    fontWeight: '900',
  },
  decisionTitle: {
    color: '#fff2e9',
    fontSize: 26,
    lineHeight: 29,
    fontWeight: '900',
    flexShrink: 1,
  },
  decisionSummary: {
    color: 'rgba(255,240,237,0.76)',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 9,
  },
  decisionBottomRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  tempRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    justifyContent: 'flex-end',
    minWidth: 92,
    flexShrink: 0,
  },
  temperature: {
    color: '#fff2e9',
    fontSize: 62,
    lineHeight: 64,
    fontWeight: '900',
  },
  degree: {
    color: '#fff2e9',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 13,
    marginLeft: 2,
  },
  centerAnswer: {
    position: 'absolute',
    top: 52,
    left: '50%',
    marginLeft: -66,
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: '#f5fbff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
  },
  centerAnswerTitle: {
    color: '#192333',
    fontSize: 28,
    lineHeight: 29,
    fontWeight: '900',
    marginTop: 3,
  },
  centerAnswerCaption: {
    color: 'rgba(25,35,51,0.64)',
    fontSize: 11,
    fontWeight: '900',
  },
  condition: {
    color: '#fffdf7',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 15,
    marginLeft: 14,
  },
  signalGrid: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 8,
  },
  signalItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    borderRadius: 16,
    backgroundColor: 'rgba(255,240,237,0.13)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.14)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 3,
  },
  signalLabel: {
    color: 'rgba(255,240,237,0.64)',
    fontSize: 10,
    fontWeight: '900',
  },
  signalValue: {
    color: '#fff2e9',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
    flexShrink: 1,
  },
  sectionTitle: {
    marginTop: 16,
    marginBottom: 10,
  },
  sectionHeading: {
    color: '#fff7ee',
    fontSize: 18,
    fontWeight: '900',
  },
  sectionCaption: {
    color: '#bdaab4',
    marginTop: 5,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  sourceGrid: {
    gap: 9,
  },
  mockSection: {
    marginTop: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(245,234,215,0.075)',
    padding: 16,
  },
  mockSectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  mockSectionTitle: {
    color: '#fff2e9',
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
  },
  mockSectionButton: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(255,240,237,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  mockSectionButtonText: {
    color: '#fff2e9',
    fontSize: 11,
    fontWeight: '900',
  },
  reasonSummary: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,211,107,0.24)',
    backgroundColor: 'rgba(32,19,28,0.58)',
    padding: 13,
    marginBottom: 10,
  },
  reasonSummaryTitle: {
    color: '#fff2e9',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  reasonSummaryText: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 5,
  },
  evidenceRow: {
    minHeight: 64,
    borderRadius: 17,
    backgroundColor: 'rgba(32,19,28,0.58)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  evidenceContent: {
    flex: 1,
    minWidth: 0,
  },
  evidenceName: {
    color: '#fff2e9',
    fontSize: 14,
    fontWeight: '900',
  },
  evidenceSub: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  sourceWeatherPillCompact: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(255,240,237,0.08)',
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  miniWeatherDrawing: {
    width: 28,
    height: 28,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniSunHalo: {
    position: 'absolute',
    width: 27,
    height: 27,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    opacity: 0.78,
  },
  miniSunCore: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  miniCloudBase: {
    position: 'absolute',
    left: 3,
    top: 10,
    width: 22,
    height: 13,
    borderRadius: 9,
  },
  miniCloudPuff: {
    position: 'absolute',
    left: 7,
    top: 4,
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  miniCloudSmall: {
    position: 'absolute',
    right: 2,
    top: 11,
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  miniRainDrops: {
    position: 'absolute',
    left: 8,
    top: 22,
    width: 14,
    height: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    transform: [{ rotate: '-14deg' }],
  },
  miniRainDrop: {
    width: 3,
    height: 9,
    borderRadius: 2,
  },
  miniRainDropLower: {
    marginTop: 3,
  },
  miniSnowDots: {
    position: 'absolute',
    left: 7,
    top: 22,
    width: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  miniSnowDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ffffff',
  },
  miniThunder: {
    position: 'absolute',
    left: 10,
    top: 16,
    width: 12,
    height: 18,
  },
  miniThunderTop: {
    position: 'absolute',
    top: 0,
    left: 5,
    width: 5,
    height: 13,
    borderRadius: 2,
    backgroundColor: '#ffd33d',
    transform: [{ rotate: '28deg' }],
  },
  miniThunderBottom: {
    position: 'absolute',
    top: 8,
    left: 1,
    width: 5,
    height: 13,
    borderRadius: 2,
    backgroundColor: '#ffd33d',
    transform: [{ rotate: '28deg' }],
  },
  miniFogLines: {
    position: 'absolute',
    left: 2,
    top: 21,
    width: 24,
    gap: 4,
  },
  miniFogLine: {
    height: 2,
    borderRadius: 2,
  },
  miniFogLineShort: {
    width: 16,
    height: 2,
    borderRadius: 2,
    marginLeft: 5,
  },
  sourceTempCompact: {
    color: '#fff2e9',
    fontSize: 13,
    fontWeight: '900',
  },
  liveEvidenceBadge: {
    minHeight: 29,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(255,240,237,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
    maxWidth: 108,
  },
  liveEvidenceBadgeText: {
    color: '#fff2e9',
    fontSize: 11,
    fontWeight: '900',
  },
  sourceForecastCard: {
    borderRadius: 22,
    backgroundColor: '#fff7ee',
    padding: 14,
    gap: 13,
  },
  sourceForecastHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sourceForecastTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  sourceLogoFrame: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#fffdf7',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#eadde3',
    overflow: 'hidden',
  },
  sourceLogoBehind: {
    position: 'absolute',
    color: '#2f1822',
    fontSize: 12,
    fontWeight: '900',
  },
  sourceLogoImage: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  sourceLogoFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceLogoFallbackText: {
    color: '#fffdf7',
    fontSize: 13,
    fontWeight: '900',
  },
  sourceForecastMain: {
    minHeight: 76,
    borderRadius: 18,
    backgroundColor: '#eadde3',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
  },
  sourceWeatherIcon: {
    width: 48,
    height: 48,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceWeatherIconText: {
    color: '#fffdf7',
    fontSize: 15,
    fontWeight: '900',
  },
  sourceForecastReading: {
    flex: 1,
    minWidth: 0,
  },
  sourceTempLarge: {
    color: '#2f1822',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  sourceConditionLarge: {
    color: '#6b5a62',
    fontSize: 13,
    fontWeight: '900',
    marginTop: 3,
  },
  reasonCard: {
    borderRadius: 22,
    backgroundColor: '#2f1a24',
    borderWidth: 1,
    borderColor: 'rgba(255,247,238,0.08)',
    padding: 17,
    marginBottom: 10,
  },
  reasonKicker: {
    color: '#f5cf76',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  reasonText: {
    color: '#fff7ee',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '800',
  },
  reasonSignalList: {
    gap: 8,
    marginTop: 14,
  },
  reasonSignalItem: {
    borderRadius: 14,
    backgroundColor: 'rgba(255,247,238,0.09)',
    padding: 11,
  },
  reasonSignalLabel: {
    color: '#f5cf76',
    fontSize: 11,
    fontWeight: '900',
  },
  reasonSignalValue: {
    color: '#fff7ee',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  sourceCard: {
    borderRadius: 20,
    backgroundColor: '#fff7ee',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sourceMark: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceMarkText: {
    color: '#fffdf7',
    fontSize: 13,
    fontWeight: '900',
  },
  sourceContent: {
    flex: 1,
    minWidth: 0,
  },
  sourceName: {
    color: '#2f1822',
    fontSize: 14,
    fontWeight: '900',
  },
  sourceDetail: {
    color: '#4a2633',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 4,
  },
  sourceWeatherPill: {
    minWidth: 62,
    borderRadius: 16,
    backgroundColor: '#eadde3',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  sourceTemp: {
    color: '#2f1822',
    fontSize: 16,
    fontWeight: '900',
  },
  sourceCondition: {
    color: '#6b5a62',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  forecastPanel: {
    borderRadius: 18,
    backgroundColor: 'rgba(32,19,28,0.58)',
    overflow: 'hidden',
  },
  forecastLead: {
    padding: 13,
    backgroundColor: 'rgba(255,240,237,0.08)',
  },
  forecastLeadLabel: {
    color: '#ffd36b',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 5,
  },
  forecastLeadText: {
    color: '#fff2e9',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
  },
  forecastHint: {
    borderRadius: 15,
    backgroundColor: 'rgba(255,240,237,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.12)',
    padding: 11,
    marginTop: 10,
  },
  forecastHintLabel: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '900',
  },
  forecastHintText: {
    color: '#fff2e9',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  forecastRows: {
    padding: 10,
    gap: 9,
  },
  forecastRow: {
    minHeight: 66,
    borderRadius: 17,
    backgroundColor: 'rgba(255,240,237,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
  },
  forecastMark: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forecastMarkText: {
    fontSize: 14,
    fontWeight: '900',
  },
  forecastWeatherIconFrame: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: 'rgba(255,240,237,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  forecastMain: {
    flex: 1,
    minWidth: 0,
  },
  forecastTime: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '800',
  },
  forecastTitle: {
    color: '#fff2e9',
    fontSize: 13,
    fontWeight: '900',
    marginTop: 3,
  },
  forecastSide: {
    alignItems: 'flex-end',
  },
  forecastTemp: {
    color: '#fff2e9',
    fontSize: 13,
    fontWeight: '900',
  },
  forecastNote: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
  },
  reportBox: {
    borderRadius: 15,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 0,
    paddingLeft: 13,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    minHeight: 42,
  },
  localReportCard: {
    marginTop: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(245,234,215,0.075)',
    padding: 14,
    gap: 10,
  },
  localReportHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  localReportTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  localReportTitleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: 7,
  },
  localReportTitle: {
    color: '#fff2e9',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    flexShrink: 1,
  },
  localReportPlace: {
    color: 'rgba(255,240,237,0.56)',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '900',
  },
  localReportCaption: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    marginTop: 4,
  },
  localOptions: {
    gap: 7,
  },
  localOptionChip: {
    minHeight: 31,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    backgroundColor: 'rgba(32,19,28,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  localOptionChipActive: {
    borderColor: '#ffd36b',
    backgroundColor: '#ffd36b',
  },
  localOptionText: {
    color: '#fff2e9',
    fontSize: 11,
    fontWeight: '900',
  },
  localOptionTextActive: {
    color: '#301a22',
  },
  localReportStatus: {
    minHeight: 16,
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 8,
  },
  reportInput: {
    flex: 1,
    color: '#fff2e9',
    fontSize: 12,
    fontWeight: '800',
    minHeight: 42,
  },
  primaryButton: {
    borderRadius: 15,
    backgroundColor: '#ffd36b',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: '#301a22',
    fontSize: 12,
    fontWeight: '900',
  },
  reportList: {
    marginTop: 10,
    gap: 9,
  },
  reportItem: {
    borderRadius: 17,
    backgroundColor: 'rgba(32,19,28,0.58)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reportContent: {
    flex: 1,
    minWidth: 0,
  },
  reportMeta: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 5,
  },
  reportBody: {
    color: '#fff2e9',
    fontSize: 13,
    fontWeight: '900',
    flexShrink: 1,
  },
  reportCondition: {
    color: '#ffd36b',
    fontSize: 11,
    fontWeight: '900',
  },
  emptyState: {
    marginTop: 12,
    borderRadius: 22,
    backgroundColor: '#2f1a24',
    borderWidth: 1,
    borderColor: 'rgba(255,247,238,0.08)',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  emptyStateMark: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: '#fff7ee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateMarkText: {
    color: '#4a2633',
    fontSize: 20,
    fontWeight: '900',
  },
  emptyStateContent: {
    flex: 1,
    minWidth: 0,
  },
  emptyStateTitle: {
    color: '#fff7ee',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
  },
  emptyStateBody: {
    color: '#bdaab4',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: 5,
  },
  emptyStateAction: {
    color: '#f5cf76',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
    marginTop: 9,
  },
  mapCard: {
    height: 500,
    borderRadius: 30,
    backgroundColor: 'rgba(245,234,215,0.075)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 14,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    position: 'relative',
  },
  mapGlowZoneOne: {
    position: 'absolute',
    left: 32,
    top: 164,
    width: 124,
    height: 82,
    borderRadius: 46,
    backgroundColor: 'rgba(107,215,255,0.22)',
    opacity: 0.9,
    transform: [{ rotate: '-8deg' }],
  },
  mapGlowZoneTwo: {
    position: 'absolute',
    right: 30,
    top: 82,
    width: 104,
    height: 122,
    borderRadius: 54,
    backgroundColor: 'rgba(255,191,102,0.16)',
    opacity: 0.95,
    transform: [{ rotate: '12deg' }],
  },
  mapRoadOne: {
    position: 'absolute',
    left: 24,
    top: 126,
    width: 330,
    height: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(245,234,215,0.18)',
    transform: [{ rotate: '22deg' }],
  },
  mapRoadTwo: {
    position: 'absolute',
    left: 88,
    top: 82,
    width: 250,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(245,234,215,0.16)',
    transform: [{ rotate: '-52deg' }],
  },
  mapRoadThree: {
    position: 'absolute',
    left: 15,
    top: 332,
    width: 310,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(245,234,215,0.14)',
    transform: [{ rotate: '-38deg' }],
  },
  mapPin: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#f25a38',
    borderWidth: 4,
    borderColor: '#fff7ee',
  },
  mapPinOne: {
    top: 80,
    left: 70,
  },
  mapPinTwo: {
    top: 150,
    right: 82,
    backgroundColor: '#8cc9ff',
  },
  mapPinThree: {
    bottom: 126,
    left: 148,
    backgroundColor: '#f5cf76',
  },
  mapTitle: {
    color: '#fff7ee',
    fontSize: 27,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: 10,
  },
  mapCaption: {
    color: 'rgba(255,240,237,0.66)',
    marginTop: 7,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  mapOverlay: {
    borderRadius: 24,
    backgroundColor: 'rgba(32,19,28,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 16,
  },
  mapOverlayTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mapRadiusChip: {
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: '#ffd36b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  mapRadiusChipText: {
    color: '#301a22',
    fontSize: 11,
    fontWeight: '900',
  },
  mapOverlayCount: {
    color: 'rgba(255,240,237,0.64)',
    fontSize: 12,
    fontWeight: '900',
  },
  mapKicker: {
    color: '#f6c453',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  mapReportMarker: {
    position: 'absolute',
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.26,
    shadowRadius: 28,
  },
  mapReportMarkerActive: {
    transform: [{ scale: 1.08 }],
    borderWidth: 3,
    borderColor: '#fff7ee',
  },
  mapReportMarkerText: {
    color: '#2f1822',
    fontSize: 15,
    fontWeight: '900',
  },
  mapCurrentLocation: {
    position: 'absolute',
    top: '46%',
    left: '50%',
    width: 34,
    height: 34,
    borderRadius: 17,
    marginLeft: -17,
    marginTop: -17,
    backgroundColor: 'rgba(255,211,107,0.13)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,211,107,0.42)',
  },
  mapCurrentDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ffd36b',
    borderWidth: 2,
    borderColor: '#fff2e9',
  },
  mapStats: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  mapStatItem: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#fff7ee',
    padding: 13,
  },
  mapStatValue: {
    color: '#2f1822',
    fontSize: 18,
    fontWeight: '900',
  },
  mapStatLabel: {
    color: '#8f7f87',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 4,
  },
  mapSelectedCard: {
    marginTop: 12,
    borderRadius: 22,
    backgroundColor: 'rgba(245,234,215,0.075)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapSelectedKicker: {
    color: 'rgba(255,240,237,0.56)',
    fontSize: 12,
    fontWeight: '900',
  },
  mapSelectedPlace: {
    color: '#fff2e9',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 5,
  },
  mapSelectedBody: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    marginTop: 7,
    maxWidth: 230,
  },
  mapSelectedCondition: {
    color: '#ffd36b',
    fontSize: 13,
    fontWeight: '900',
  },
  mapListHeader: {
    marginTop: 18,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mapListTitle: {
    color: '#fff2e9',
    fontSize: 18,
    fontWeight: '900',
  },
  mapListAction: {
    color: '#ffd36b',
    fontSize: 12,
    fontWeight: '900',
  },
  mapReportItem: {
    borderRadius: 18,
    backgroundColor: 'rgba(32,19,28,0.58)',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapReportItemActive: {
    borderWidth: 1,
    borderColor: '#ffd36b',
    backgroundColor: 'rgba(255,211,107,0.10)',
  },
  mapReportContent: {
    flex: 1,
    minWidth: 0,
  },
  requestCard: {
    borderRadius: 26,
    backgroundColor: 'rgba(245,234,215,0.075)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 16,
    marginBottom: 14,
    overflow: 'hidden',
  },
  requestKicker: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: '#ffd36b',
    color: '#301a22',
    fontSize: 12,
    fontWeight: '900',
    paddingHorizontal: 11,
    paddingTop: 7,
  },
  requestTitle: {
    color: '#fff2e9',
    fontSize: 25,
    lineHeight: 27,
    fontWeight: '900',
    marginTop: 12,
    marginBottom: 14,
  },
  reportGuide: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  reportStep: {
    flex: 1,
    minHeight: 66,
    borderRadius: 17,
    backgroundColor: 'rgba(32,19,28,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 10,
  },
  reportStepLabel: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 11,
    fontWeight: '900',
  },
  reportStepText: {
    color: '#fff2e9',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  requestForm: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  requestInput: {
    borderRadius: 15,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    color: '#fff2e9',
    minHeight: 42,
    paddingHorizontal: 13,
    fontSize: 12,
    fontWeight: '800',
    flex: 1,
  },
  requestSubmitButton: {
    borderRadius: 15,
    backgroundColor: '#ffd36b',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  requestSubmitText: {
    color: '#301a22',
    fontSize: 12,
    fontWeight: '900',
  },
  reportSectionHeader: {
    marginTop: 18,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportSectionTitle: {
    color: '#fff7ee',
    fontSize: 20,
    fontWeight: '900',
  },
  reportSectionAction: {
    color: '#f5cf76',
    fontSize: 12,
    fontWeight: '900',
  },
  requestList: {
    gap: 10,
  },
  requestListItem: {
    borderRadius: 19,
    backgroundColor: 'rgba(32,19,28,0.62)',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  requestListItemActive: {
    backgroundColor: 'rgba(32,19,28,0.72)',
    borderColor: '#ffd36b',
  },
  requestMark: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  requestMarkText: {
    color: '#fffdf7',
    fontSize: 14,
    fontWeight: '900',
  },
  requestListContent: {
    flex: 1,
    minWidth: 0,
  },
  requestQuestion: {
    color: '#fff7ee',
    fontSize: 15,
    fontWeight: '900',
  },
  requestQuestionActive: {
    color: '#fff2e9',
  },
  requestHint: {
    color: '#bdaab4',
    marginTop: 6,
    fontSize: 13,
  },
  requestHintActive: {
    color: 'rgba(255,240,237,0.66)',
  },
  requestStatus: {
    color: '#f5cf76',
    fontSize: 11,
    fontWeight: '900',
  },
  requestStatusActive: {
    color: '#ffd36b',
  },
  replyBox: {
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(255,122,138,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,122,138,0.34)',
    padding: 12,
  },
  replyEyebrow: {
    color: '#ffd36b',
    fontSize: 12,
    fontWeight: '900',
  },
  replyQuestion: {
    color: '#fff2e9',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
    marginTop: 7,
  },
  replyInput: {
    marginTop: 12,
    minHeight: 96,
    borderRadius: 16,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    color: '#fff2e9',
    fontSize: 13,
    lineHeight: 20,
    padding: 14,
    textAlignVertical: 'top',
  },
  replySubmitButton: {
    marginTop: 12,
    minHeight: 42,
    borderRadius: 15,
    backgroundColor: '#ffd36b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  replySubmitText: {
    color: '#301a22',
    fontSize: 12,
    fontWeight: '900',
  },
  replyNotice: {
    color: 'rgba(255,240,237,0.66)',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 10,
  },
  liveReportList: {
    gap: 10,
  },
  liveReportItem: {
    borderRadius: 18,
    backgroundColor: 'rgba(32,19,28,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.08)',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  liveReportPlace: {
    color: '#fff7ee',
    fontSize: 14,
    fontWeight: '900',
  },
  liveReportBody: {
    color: '#bdaab4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 5,
  },
  liveReportCondition: {
    color: '#f5cf76',
    fontSize: 12,
    fontWeight: '900',
  },
  compareHero: {
    borderRadius: 28,
    backgroundColor: 'rgba(245,234,215,0.075)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 17,
    marginBottom: 14,
  },
  compareKicker: {
    color: '#ffd36b',
    fontSize: 12,
    fontWeight: '900',
  },
  compareTitle: {
    color: '#fff2e9',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: 10,
    marginBottom: 16,
  },
  compareContextBar: {
    borderRadius: 16,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.12)',
    padding: 12,
    marginBottom: 14,
  },
  compareContextLabel: {
    color: 'rgba(255,240,237,0.6)',
    fontSize: 11,
    fontWeight: '900',
  },
  compareContextText: {
    color: '#fff2e9',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  compareSummaryList: {
    gap: 10,
  },
  compareSummaryCard: {
    minHeight: 70,
    borderRadius: 18,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.10)',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  compareServiceMark: {
    width: 42,
    height: 42,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareServiceMarkText: {
    color: '#fffdf7',
    fontSize: 13,
    fontWeight: '900',
  },
  compareServiceLogoFrame: {
    width: 42,
    height: 42,
    borderRadius: 17,
    backgroundColor: '#fffdf7',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  compareServiceLogoImage: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  compareSummaryContent: {
    flex: 1,
    minWidth: 0,
  },
  compareSummaryName: {
    color: '#fff2e9',
    fontSize: 14,
    fontWeight: '900',
  },
  compareSummaryText: {
    color: '#bdaab4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  compareSummaryValue: {
    minWidth: 50,
    maxWidth: 62,
    borderRadius: 15,
    backgroundColor: 'rgba(255,211,107,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,211,107,0.28)',
    paddingVertical: 7,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  compareSummaryValueText: {
    color: '#ffd36b',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareSummaryWeatherBadge: {
    width: 74,
    minHeight: 72,
    borderRadius: 17,
    backgroundColor: 'rgba(255,211,107,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,211,107,0.28)',
    paddingVertical: 7,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareSummaryWeatherIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  compareSummaryWeatherText: {
    color: '#fff2e9',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareSummarySub: {
    color: 'rgba(255,240,237,0.56)',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  compareMode: {
    borderRadius: 20,
    backgroundColor: '#37202a',
    padding: 5,
    flexDirection: 'row',
    marginBottom: 14,
  },
  compareModeButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareModeButtonActive: {
    backgroundColor: '#f6c453',
  },
  compareModeText: {
    color: '#d8c9d0',
    fontSize: 14,
    fontWeight: '900',
  },
  compareModeTextActive: {
    color: '#2f1822',
  },
  comparePanel: {
    borderRadius: 24,
    backgroundColor: 'rgba(245,234,215,0.075)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.17)',
    padding: 12,
  },
  comparePanelTitle: {
    paddingHorizontal: 4,
    paddingVertical: 6,
    marginBottom: 8,
  },
  comparePanelHeading: {
    color: '#fff2e9',
    fontSize: 20,
    fontWeight: '900',
  },
  comparePanelCaption: {
    color: '#bdaab4',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  compareRows: {
    gap: 10,
  },
  compareTableFrame: {
    minHeight: 334,
    borderRadius: 19,
    backgroundColor: 'rgba(32,19,28,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,240,237,0.10)',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  compareTableServiceColumn: {
    width: 96,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,240,237,0.10)',
    backgroundColor: 'rgba(32,19,28,0.70)',
  },
  compareTableCorner: {
    height: 46,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,240,237,0.10)',
  },
  compareTableCornerText: {
    color: '#ffd36b',
    fontSize: 12,
    fontWeight: '900',
  },
  compareTableServiceCell: {
    height: 96,
    paddingHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,240,237,0.08)',
  },
  compareTableServiceIconFrame: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fffdf7',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 7,
  },
  compareTableServiceIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  compareTableServiceText: {
    color: '#fff2e9',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  compareTableScrollContent: {
    paddingRight: 10,
  },
  compareForecastColumn: {
    width: 108,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,240,237,0.08)',
  },
  compareForecastColumnHead: {
    height: 46,
    paddingHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,240,237,0.10)',
  },
  compareForecastColumnLabel: {
    color: '#ffd36b',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareForecastCell: {
    height: 96,
    paddingHorizontal: 7,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,240,237,0.08)',
  },
  compareForecastIconFrame: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareForecastMarkText: {
    color: '#fffdf7',
    fontSize: 12,
    fontWeight: '900',
  },
  compareForecastTextBox: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
  },
  compareForecastWeather: {
    color: '#fff2e9',
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareForecastDetail: {
    color: '#bdaab4',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '800',
    marginTop: 1,
    textAlign: 'center',
  },
  compareDifferenceList: {
    gap: 10,
  },
  compareInsightCard: {
    borderRadius: 20,
    backgroundColor: '#fff7ee',
    padding: 15,
    marginBottom: 12,
  },
  compareInsightLabel: {
    color: '#8f7f87',
    fontSize: 12,
    fontWeight: '900',
  },
  compareInsightText: {
    color: '#2f1822',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    marginTop: 6,
  },
  compareDifferenceItem: {
    borderRadius: 18,
    backgroundColor: '#2f1a24',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  compareDifferenceContent: {
    flex: 1,
    minWidth: 0,
  },
  compareDifferenceName: {
    color: '#fff7ee',
    fontSize: 14,
    fontWeight: '900',
  },
  compareDifferenceBody: {
    color: '#bdaab4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 4,
  },
  compareDifferenceBadge: {
    color: '#f5cf76',
    fontSize: 11,
    fontWeight: '900',
  },
  compareTable: {
    borderRadius: 22,
    backgroundColor: '#fff7ee',
    overflow: 'hidden',
  },
  compareRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eadde3',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  compareTime: {
    color: '#2f1822',
    width: 42,
    fontSize: 13,
    fontWeight: '900',
  },
  compareCell: {
    color: '#4a2633',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  bottomTabs: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 10,
    borderRadius: 24,
    backgroundColor: '#fff7ee',
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 7,
  },
  tabButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  tabButtonActive: {
    backgroundColor: '#2b171f',
  },
  tabText: {
    color: '#6b5a62',
    fontSize: 11,
    fontWeight: '900',
  },
  tabTextActive: {
    color: '#fff7ee',
  },
  tabIconVector: {
    height: 23,
    marginBottom: 1,
  },
});
