import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#eff1ee',
  },
  app: {
    flex: 1,
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    backgroundColor: '#f4f5f2',
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: '#242424',
    fontSize: 20,
    fontWeight: '900',
  },
  headerSub: {
    color: 'rgba(36,36,36,0.60)',
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  scrollContent: {
    paddingBottom: 0,
  },
  refreshButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshText: {
    color: '#242424',
    fontSize: 25,
  },
  searchBox: {
    marginHorizontal: 18,
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 15,
    paddingRight: 0,
  },
  searchIcon: {
    color: 'rgba(36,36,36,0.64)',
    fontSize: 18,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#242424',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 20,
    paddingVertical: 9,
  },
  searchSubmit: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#242424',
  },
  searchSubmitDisabled: {
    opacity: 0.5,
  },
  searchSubmitText: {
    color: '#eee9dd',
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 26,
  },
  searchSuggestionList: {
    gap: 7,
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 2,
  },
  searchSuggestionChip: {
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(205,201,187,0.54)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  searchSuggestionChipActive: {
    backgroundColor: '#242424',
  },
  searchSuggestionChipDisabled: {
    opacity: 0.55,
  },
  searchSuggestionText: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '900',
  },
  searchSuggestionTextActive: {
    color: '#f4f5f2',
  },
  placeCandidatePanel: {
    marginHorizontal: 18,
    marginTop: 8,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 10,
    gap: 6,
  },
  placeCandidateTitle: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 4,
    paddingBottom: 2,
  },
  placeCandidateRow: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#eef0ed',
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  placeCandidateTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  placeCandidateName: {
    color: '#242424',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  placeCandidateSubtitle: {
    color: 'rgba(36,36,36,0.55)',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
    marginTop: 2,
  },
  placeCandidateAction: {
    color: '#f4f5f2',
    backgroundColor: '#242424',
    borderRadius: 14,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: '900',
  },
  dataStatusBanner: {
    marginHorizontal: 18,
    marginTop: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(205,201,187,0.58)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dataStatusBannerLoading: {
    borderColor: 'transparent',
  },
  dataStatusBannerWarning: {
    backgroundColor: '#242424',
    borderColor: 'transparent',
  },
  dataStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#242424',
  },
  dataStatusDotLoading: {
    backgroundColor: '#dcd8cb',
  },
  dataStatusContent: {
    flex: 1,
    minWidth: 0,
  },
  dataStatusLabel: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  dataStatusMessage: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 3,
  },
  dataStatusLabelWarning: {
    color: '#f4f5f2',
  },
  dataStatusMessageWarning: {
    color: 'rgba(244,245,242,0.78)',
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 224,
  },
  searchResultCard: {
    borderRadius: 22,
    backgroundColor: '#f3f4f1',
    padding: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  searchResultMain: {
    flex: 1,
    minWidth: 0,
  },
  searchResultKicker: {
    color: '#757a72',
    fontSize: 11,
    fontWeight: '900',
  },
  searchResultTitle: {
    color: '#2f1822',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  searchResultQuery: {
    color: '#62665f',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  searchResultChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  searchResultChip: {
    borderRadius: 14,
    backgroundColor: '#eef0ed',
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  searchResultChipLabel: {
    color: '#757a72',
    fontSize: 10,
    fontWeight: '900',
  },
  searchResultChipValue: {
    color: '#2f1822',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  searchResultNote: {
    borderRadius: 14,
    backgroundColor: '#f1ece1',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginTop: 10,
  },
  searchResultNoteWarning: {
    backgroundColor: '#fff0d1',
  },
  searchResultNoteText: {
    color: '#62665f',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  searchResultNoteWarningText: {
    color: '#7a4217',
  },
  searchResultBadge: {
    minWidth: 58,
    minHeight: 38,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginTop: 2,
  },
  searchResultBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  weatherSwitch: {
    gap: 7,
    paddingBottom: 10,
  },
  weatherChip: {
    minWidth: 52,
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(214,210,196,0.58)',
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  weatherChipText: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '900',
  },
  weatherChipTextActive: {
    color: '#f4f5f2',
  },
  decisionCard: {
    borderRadius: 34,
    padding: 20,
    minHeight: 414,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'transparent',
    shadowColor: 'rgba(54,56,48,0.20)',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 36,
  },
  decisionCardModern: {
    borderRadius: 38,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 20,
    minHeight: 468,
  },
  decisionCardModernDark: {
    shadowColor: 'rgba(42,38,54,0.40)',
  },
  decisionModernWash: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    top: -134,
    left: -84,
    backgroundColor: 'rgba(255,255,255,0.24)',
  },
  decisionModernTop: {
    position: 'relative',
    zIndex: 4,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  decisionModernPill: {
    flex: 1,
    minHeight: 34,
    maxWidth: 218,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  decisionModernPillDark: {
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  decisionModernPillText: {
    color: 'rgba(36,36,36,0.62)',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  decisionModernTempRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexShrink: 0,
  },
  decisionModernTemp: {
    color: '#242424',
    fontSize: 58,
    lineHeight: 58,
    fontWeight: '900',
  },
  decisionModernDegree: {
    color: '#242424',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 9,
    marginLeft: 2,
  },
  decisionModernArtStage: {
    position: 'relative',
    zIndex: 3,
    height: 158,
    marginTop: 4,
    marginBottom: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decisionModernCopy: {
    position: 'relative',
    zIndex: 4,
    marginTop: 2,
  },
  decisionModernCaption: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
  },
  decisionModernTitle: {
    color: '#242424',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    marginTop: 6,
  },
  decisionModernSummary: {
    color: 'rgba(36,36,36,0.64)',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    marginTop: 10,
  },
  decisionModernSignals: {
    position: 'relative',
    zIndex: 4,
    marginTop: 18,
    flexDirection: 'row',
    gap: 8,
  },
  decisionModernSignal: {
    flex: 1,
    minHeight: 60,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.42)',
    paddingHorizontal: 11,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  decisionModernSignalDark: {
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  decisionModernSignalLabel: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
  },
  decisionModernSignalValue: {
    color: '#242424',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  decisionModernTextDark: {
    color: '#f7f7f1',
  },
  decisionModernTextDarkSoft: {
    color: 'rgba(247,247,241,0.70)',
  },
  decisionPosterCard: {
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    minHeight: 474,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    shadowColor: 'rgba(0,0,0,0.34)',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.24,
    shadowRadius: 48,
  },
  decisionPosterCardDark: {
    shadowColor: 'rgba(0,0,0,0.48)',
  },
  decisionPosterTop: {
    position: 'relative',
    zIndex: 4,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  decisionPosterMetaBlock: {
    flex: 1,
    minWidth: 0,
  },
  decisionPosterMeta: {
    color: 'rgba(32,34,37,0.58)',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
  },
  decisionPosterPlace: {
    color: '#202225',
    fontSize: 17,
    lineHeight: 20,
    fontWeight: '900',
    marginTop: 2,
  },
  decisionPosterVertical: {
    color: 'rgba(32,34,37,0.54)',
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
    transform: [{ rotate: '90deg' }],
    width: 86,
    marginRight: -32,
    marginTop: 28,
  },
  decisionPosterScene: {
    position: 'relative',
    zIndex: 2,
    height: 230,
    marginHorizontal: -18,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  posterWeatherArt: {
    width: 320,
    height: 230,
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterWeatherImage: {
    width: 320,
    height: 230,
  },
  posterWeatherClear: {
    width: 300,
  },
  posterWeatherCloud: {
    width: 318,
  },
  posterWeatherRain: {
    width: 300,
  },
  posterWeatherStorm: {
    width: 318,
  },
  posterWeatherSnow: {
    width: 318,
  },
  posterWeatherFog: {
    width: 318,
  },
  decisionPosterTempRow: {
    position: 'relative',
    zIndex: 4,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 0,
  },
  decisionPosterTemp: {
    color: '#202225',
    fontSize: 58,
    lineHeight: 56,
    fontWeight: '300',
    letterSpacing: -1,
  },
  decisionPosterDegree: {
    color: '#202225',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    marginTop: 8,
    marginLeft: 2,
  },
  decisionPosterCopy: {
    position: 'relative',
    zIndex: 4,
    marginTop: 12,
  },
  decisionPosterCaption: {
    color: 'rgba(32,34,37,0.62)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  decisionPosterTitle: {
    color: '#202225',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
    marginTop: 5,
  },
  decisionPosterSummary: {
    color: 'rgba(32,34,37,0.66)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 8,
  },
  decisionPosterSignals: {
    position: 'relative',
    zIndex: 4,
    marginTop: 16,
    flexDirection: 'row',
    gap: 8,
  },
  decisionPosterSignal: {
    flex: 1,
    minHeight: 58,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(32,34,37,0.16)',
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 10,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  decisionPosterSignalDark: {
    borderColor: 'rgba(243,243,232,0.16)',
    backgroundColor: 'rgba(243,243,232,0.08)',
  },
  decisionPosterSignalLabel: {
    color: 'rgba(32,34,37,0.58)',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
  },
  decisionPosterSignalValue: {
    color: '#202225',
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '900',
    marginTop: 3,
  },
  decisionPosterTextDark: {
    color: '#f3f3e8',
  },
  decisionPosterTextSoftDark: {
    color: 'rgba(243,243,232,0.66)',
  },
  figmaWeatherCard: {
    borderRadius: 28,
    minHeight: 610,
    paddingHorizontal: 28,
    paddingTop: 30,
    paddingBottom: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: 'rgba(35,45,60,0.32)',
    shadowOffset: { width: 0, height: 30 },
    shadowOpacity: 0.26,
    shadowRadius: 55,
  },
  figmaWeatherGlow: {
    position: 'absolute',
    top: -90,
    right: -92,
    width: 230,
    height: 230,
    borderRadius: 115,
  },
  figmaWeatherTop: {
    position: 'relative',
    zIndex: 3,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  figmaWeatherLocation: {
    flex: 1,
    minWidth: 0,
  },
  figmaWeatherEyebrow: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  figmaWeatherCity: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 3,
  },
  figmaWeatherTime: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 2,
  },
  figmaWeatherScene: {
    position: 'relative',
    zIndex: 2,
    height: 178,
    marginTop: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  figmaArtworkWrap: {
    position: 'relative',
    width: 190,
    height: 190,
    alignItems: 'center',
    justifyContent: 'center',
  },
  figmaLineArt: {
    width: 168,
    height: 168,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  figmaMotionLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 190,
    height: 190,
  },
  figmaMotionRainDrop: {
    position: 'absolute',
    width: 8,
    height: 34,
    borderRadius: 8,
    transform: [{ rotate: '16deg' }],
  },
  figmaMotionSnowDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  figmaMotionFlash: {
    position: 'absolute',
    left: 40,
    top: 28,
    width: 112,
    height: 112,
    borderRadius: 56,
    opacity: 0.24,
  },
  figmaMotionFogLine: {
    position: 'absolute',
    left: 26,
    width: 138,
    height: 8,
    borderRadius: 8,
    opacity: 0.48,
  },
  figmaMotionFogLineShort: {
    left: 48,
    width: 96,
    opacity: 0.58,
  },
  figmaMotionTyphoon: {
    position: 'absolute',
    left: 47,
    top: 47,
    width: 96,
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  figmaMotionTyphoonRing: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 2,
    borderStyle: 'dashed',
    opacity: 0.32,
  },
  figmaMotionHalo: {
    position: 'absolute',
    left: 30,
    top: 30,
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 10,
  },
  figmaSunGlow: {
    position: 'absolute',
    width: 86,
    height: 86,
    borderRadius: 43,
    borderWidth: 1,
    opacity: 0.16,
  },
  figmaSunCircle: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
  },
  figmaSunInner: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    opacity: 0.45,
  },
  figmaSunRay: {
    position: 'absolute',
    width: 2,
    height: 24,
    borderRadius: 2,
  },
  figmaRayTop: {
    top: 12,
  },
  figmaRayRight: {
    right: 12,
    transform: [{ rotate: '90deg' }],
  },
  figmaRayBottom: {
    bottom: 12,
  },
  figmaRayLeft: {
    left: 12,
    transform: [{ rotate: '90deg' }],
  },
  figmaRayDiagA: {
    top: 28,
    right: 32,
    transform: [{ rotate: '45deg' }],
  },
  figmaRayDiagB: {
    bottom: 28,
    right: 32,
    transform: [{ rotate: '-45deg' }],
  },
  figmaRayDiagC: {
    bottom: 28,
    left: 32,
    transform: [{ rotate: '45deg' }],
  },
  figmaRayDiagD: {
    top: 28,
    left: 32,
    transform: [{ rotate: '-45deg' }],
  },
  figmaCloudArt: {
    position: 'absolute',
    width: 132,
    height: 94,
    top: 28,
    left: 18,
  },
  figmaCloudCircle: {
    position: 'absolute',
    borderWidth: 2,
    backgroundColor: 'transparent',
  },
  figmaCloudLeft: {
    left: 0,
    top: 38,
    width: 48,
    height: 42,
    borderRadius: 24,
    borderRightWidth: 0,
  },
  figmaCloudCenter: {
    left: 34,
    top: 8,
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  figmaCloudRight: {
    right: 0,
    top: 34,
    width: 54,
    height: 46,
    borderRadius: 27,
    borderLeftWidth: 0,
  },
  figmaCloudBase: {
    position: 'absolute',
    left: 14,
    right: 8,
    bottom: 6,
    height: 2,
    borderTopWidth: 2,
  },
  figmaRainGroup: {
    position: 'absolute',
    left: 44,
    top: 96,
    width: 88,
    height: 58,
  },
  figmaRainGroupCompact: {
    top: 104,
  },
  figmaRainLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 3,
    height: 34,
    borderRadius: 2,
    transform: [{ rotate: '18deg' }],
  },
  figmaRainLineTwo: {
    left: 24,
    top: 8,
  },
  figmaRainLineThree: {
    left: 48,
    top: 0,
  },
  figmaRainLineFour: {
    left: 72,
    top: 8,
  },
  figmaBolt: {
    position: 'absolute',
    left: 67,
    top: 74,
    width: 42,
    height: 70,
    borderTopWidth: 34,
    borderRightWidth: 18,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    transform: [{ rotate: '17deg' }, { skewY: '-18deg' }],
  },
  figmaSnowflake: {
    position: 'absolute',
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '900',
  },
  figmaSnowOne: {
    left: 30,
    top: 94,
  },
  figmaSnowTwo: {
    left: 70,
    top: 108,
    fontSize: 24,
  },
  figmaSnowThree: {
    right: 24,
    top: 90,
    fontSize: 28,
  },
  figmaSnowFour: {
    left: 58,
    top: 134,
    fontSize: 20,
  },
  figmaCloudHatch: {
    position: 'absolute',
    width: 34,
    height: 2,
    borderRadius: 2,
    opacity: 0.52,
  },
  figmaHatchOne: {
    left: 58,
    top: 87,
    transform: [{ rotate: '108deg' }],
  },
  figmaHatchTwo: {
    left: 78,
    top: 88,
    transform: [{ rotate: '108deg' }],
  },
  figmaHatchThree: {
    left: 98,
    top: 87,
    transform: [{ rotate: '108deg' }],
  },
  figmaFogOne: {
    left: 22,
    top: 104,
    width: 124,
    height: 3,
  },
  figmaFogTwo: {
    left: 34,
    top: 124,
    width: 108,
    height: 3,
  },
  figmaFogThree: {
    left: 18,
    top: 144,
    width: 116,
    height: 3,
  },
  figmaWeatherTempWrap: {
    position: 'relative',
    zIndex: 3,
    alignItems: 'center',
    marginTop: -8,
  },
  figmaWeatherTempRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  figmaWeatherTemp: {
    fontSize: 76,
    lineHeight: 78,
    fontWeight: '200',
    letterSpacing: -3,
  },
  figmaWeatherDegree: {
    fontSize: 25,
    lineHeight: 30,
    fontWeight: '500',
    marginTop: 9,
    marginLeft: 3,
  },
  figmaWeatherCondition: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
    marginTop: 0,
  },
  figmaWeatherSub: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 3,
    textAlign: 'center',
  },
  figmaWeatherMessage: {
    position: 'relative',
    zIndex: 3,
    marginTop: 18,
    paddingHorizontal: 2,
  },
  figmaWeatherTitle: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  figmaWeatherSummary: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 8,
  },
  figmaWeatherStats: {
    position: 'relative',
    zIndex: 3,
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  figmaWeatherStat: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
  },
  figmaWeatherStatLabel: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  figmaWeatherStatValue: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    marginTop: 4,
    textAlign: 'center',
  },
  figmaWeatherHourly: {
    position: 'relative',
    zIndex: 3,
    marginTop: 20,
    minHeight: 78,
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
  },
  figmaWeatherHourlyContent: {
    minWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  figmaWeatherHourIntro: {
    width: 84,
    minHeight: 58,
    justifyContent: 'center',
    paddingRight: 4,
  },
  figmaWeatherHourIntroLabel: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  figmaWeatherHourIntroText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  figmaWeatherHour: {
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 42,
    minHeight: 58,
  },
  figmaWeatherHourLabel: {
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
  },
  figmaWeatherHourIcon: {
    width: 28,
    height: 28,
    marginVertical: 2,
  },
  figmaWeatherHourTrack: {
    width: 3,
    height: 26,
    borderRadius: 2,
    justifyContent: 'flex-end',
    marginTop: 5,
    marginBottom: 5,
  },
  figmaWeatherHourBar: {
    width: 3,
    borderRadius: 2,
  },
  figmaWeatherHourTemp: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
  },
  decisionModernFoot: {
    display: 'none',
    position: 'relative',
    zIndex: 4,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  decisionModernFootText: {
    flex: 1,
    minWidth: 0,
    color: 'rgba(36,36,36,0.55)',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
  },
  decisionModernFootPill: {
    minHeight: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    flexShrink: 0,
  },
  decisionModernFootPillText: {
    color: 'rgba(36,36,36,0.68)',
    fontSize: 12,
    fontWeight: '900',
  },
  decisionBackdropOrbLarge: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    opacity: 0.32,
    top: -74,
    right: -64,
  },
  decisionBackdropOrbSoft: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    opacity: 0.22,
    right: -42,
    top: -22,
    backgroundColor: 'rgba(255,255,255,0.54)',
  },
  decisionTopRow: {
    position: 'relative',
    zIndex: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  decisionPlaceBlock: {
    flex: 1,
    minWidth: 0,
  },
  decisionPlaceKicker: {
    color: 'rgba(36,36,36,0.54)',
    fontSize: 11,
    fontWeight: '900',
  },
  decisionPlaceText: {
    color: '#242424',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
    marginTop: 3,
  },
  decisionTimeBadge: {
    minHeight: 36,
    borderRadius: 18,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decisionTimeBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  decisionHeroLayout: {
    position: 'relative',
    zIndex: 2,
    minHeight: 178,
    marginTop: 26,
    flexDirection: 'row',
    alignItems: 'center',
  },
  decisionHeroTextBlock: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  decisionConditionBadge: {
    alignSelf: 'flex-start',
    minHeight: 31,
    borderRadius: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  decisionConditionBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  decisionVisualStage: {
    width: 154,
    height: 160,
    position: 'relative',
    flexShrink: 0,
  },
  decisionTempPanel: {
    position: 'relative',
    zIndex: 3,
    marginTop: 12,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.34)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  decisionUpdateBlock: {
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  decisionUpdateLabel: {
    color: 'rgba(36,36,36,0.48)',
    fontSize: 10,
    fontWeight: '900',
  },
  decisionUpdateText: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 3,
  },
  decisionArtGlow: {
    position: 'absolute',
    width: 270,
    height: 250,
    borderRadius: 135,
    opacity: 0.42,
    top: -92,
    right: -76,
  },
  decisionArtAccent: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: 105,
    opacity: 0.24,
    left: -78,
    bottom: 64,
  },
  decisionHeroArea: {
    minHeight: 212,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    marginBottom: 0,
  },
  mockCompass: {
    position: 'relative',
    zIndex: 2,
    width: 250,
    height: 218,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mockCompassAxisVertical: {
    position: 'absolute',
    width: 1,
    height: 230,
    backgroundColor: 'rgba(205,201,187,0.62)',
  },
  mockCompassAxisHorizontal: {
    position: 'absolute',
    width: 230,
    height: 1,
    backgroundColor: 'rgba(205,201,187,0.62)',
  },
  mockRingOne: {
    position: 'absolute',
    width: 232,
    height: 232,
    borderRadius: 116,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  mockRingTwo: {
    position: 'absolute',
    width: 174,
    height: 174,
    borderRadius: 87,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'transparent',
    opacity: 0.9,
  },
  mockRingThree: {
    position: 'absolute',
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 1,
    backgroundColor: 'rgba(244,245,242,0.76)',
  },
  mockNeedle: {
    position: 'absolute',
    width: 18,
    height: 98,
    borderRadius: 9,
    opacity: 0.42,
    transform: [{ rotate: '36deg' }],
  },
  decisionCompassRing: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 1,
    borderColor: 'transparent',
    top: 45,
    right: 16,
  },
  decisionCompassRingMid: {
    position: 'absolute',
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'transparent',
    top: 78,
    right: 49,
    opacity: 0.9,
  },
  decisionCompassRingSmall: {
    position: 'absolute',
    width: 122,
    height: 122,
    borderRadius: 61,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(244,245,242,0.62)',
    top: 109,
    right: 80,
  },
  decisionNeedle: {
    position: 'absolute',
    top: 119,
    right: 132,
    width: 18,
    height: 100,
    borderRadius: 8,
    opacity: 0.34,
    transform: [{ rotate: '36deg' }],
  },
  weatherArt: {
    position: 'absolute',
    top: 1,
    right: -2,
    width: 154,
    height: 154,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(24,28,24,0.24)',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
  },
  weatherHeroArt: {
    width: 220,
    height: 152,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weatherObjectImage: {
    width: 176,
    height: 150,
  },
  weatherObjectSun: {
    width: 168,
  },
  weatherObjectCloud: {
    width: 162,
  },
  weatherObjectRain: {
    width: 174,
  },
  weatherObjectThunder: {
    width: 178,
  },
  weatherObjectSnow: {
    width: 160,
  },
  weatherObjectFog: {
    width: 190,
  },
  softObjectCanvas: {
    width: 146,
    height: 140,
    position: 'relative',
    transform: [{ scale: 1.02 }],
  },
  softHeroGraphic: {
    width: 146,
    height: 140,
    position: 'relative',
    transform: [{ scale: 1.38 }],
  },
  softHeroSampleTile: {
    transform: [{ scale: 1.08 }],
  },
  softSampleTile: {
    width: 146,
    height: 140,
    borderRadius: 23,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: 'rgba(24,28,24,0.15)',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  softSampleLabelBlock: {
    position: 'absolute',
    left: 12,
    bottom: 11,
    zIndex: 5,
  },
  softSampleLabel: {
    color: '#242424',
    fontSize: 15,
    lineHeight: 17,
    fontWeight: '900',
  },
  softSampleLabelDark: {
    color: '#f8f4e9',
  },
  softSampleSubLabel: {
    color: 'rgba(36,36,36,0.56)',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    marginTop: 2,
  },
  softSampleSubLabelDark: {
    color: 'rgba(248,244,233,0.62)',
  },
  softSampleSunGroup: {
    position: 'absolute',
    left: 31,
    top: 17,
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
  },
  softSampleSunCore: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#fff36d',
    shadowColor: 'rgba(24,28,24,0.16)',
    shadowOffset: { width: 8, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  softSampleRay: {
    position: 'absolute',
    width: 24,
    height: 6,
    borderRadius: 4,
    backgroundColor: 'rgba(36,36,36,0.34)',
  },
  softSampleRayTop: {
    top: 0,
    left: 30,
    transform: [{ rotate: '90deg' }],
  },
  softSampleRayRight: {
    top: 39,
    right: -3,
  },
  softSampleRayBottom: {
    bottom: 0,
    left: 30,
    transform: [{ rotate: '90deg' }],
  },
  softSampleRayLeft: {
    top: 39,
    left: -3,
  },
  softSampleRayTopLeft: {
    top: 16,
    left: 7,
    transform: [{ rotate: '45deg' }],
  },
  softSampleRayTopRight: {
    top: 16,
    right: 7,
    transform: [{ rotate: '-45deg' }],
  },
  softSampleRayBottomRight: {
    right: 7,
    bottom: 16,
    transform: [{ rotate: '45deg' }],
  },
  softSampleRayBottomLeft: {
    left: 7,
    bottom: 16,
    transform: [{ rotate: '-45deg' }],
  },
  softSampleCloudWhite: {
    position: 'absolute',
    left: 35,
    top: 56,
    width: 72,
    height: 42,
    borderRadius: 32,
    backgroundColor: '#f8f5ec',
    shadowColor: 'rgba(24,28,24,0.10)',
    shadowOffset: { width: 7, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  softSampleCloudCircle: {
    position: 'absolute',
    left: 78,
    top: 43,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#718176',
    shadowColor: 'rgba(24,28,24,0.15)',
    shadowOffset: { width: 8, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  softSampleCloudCircleRain: {
    backgroundColor: '#0b5a7b',
  },
  softSampleCloudCircleThunder: {
    backgroundColor: '#4e5663',
  },
  softSampleCloudCircleSnow: {
    backgroundColor: '#718176',
  },
  softSampleCloudCircleFog: {
    backgroundColor: '#718176',
  },
  softSampleRainLines: {
    position: 'absolute',
    left: 53,
    top: 91,
    width: 78,
    height: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    transform: [{ rotate: '8deg' }],
  },
  softSampleRainLine: {
    width: 8,
    height: 36,
    borderRadius: 5,
    backgroundColor: 'rgba(210,242,255,0.72)',
  },
  softSampleRainLineMiddle: {
    marginTop: 8,
  },
  softSampleRainLineLast: {
    marginTop: -5,
  },
  softSampleBolt: {
    position: 'absolute',
    left: 76,
    top: 52,
    width: 48,
    height: 82,
    zIndex: 4,
  },
  softSampleBoltTop: {
    position: 'absolute',
    left: 18,
    top: 0,
    width: 20,
    height: 56,
    borderRadius: 3,
    backgroundColor: '#dce868',
    transform: [{ rotate: '24deg' }],
  },
  softSampleBoltBottom: {
    position: 'absolute',
    left: 5,
    top: 33,
    width: 20,
    height: 56,
    borderRadius: 3,
    backgroundColor: '#dce868',
    transform: [{ rotate: '24deg' }],
  },
  softSampleSnowDot: {
    position: 'absolute',
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: 'rgba(36,36,36,0.38)',
  },
  softSampleSnowDotOne: {
    left: 40,
    top: 62,
  },
  softSampleSnowDotTwo: {
    left: 112,
    top: 60,
  },
  softSampleSnowDotThree: {
    left: 75,
    top: 103,
  },
  softSampleSnowDotFour: {
    left: 100,
    top: 124,
  },
  softSampleFogLines: {
    position: 'absolute',
    left: 28,
    top: 59,
    width: 98,
    height: 78,
    zIndex: 6,
  },
  softSampleFogLine: {
    position: 'absolute',
    height: 8,
    borderRadius: 6,
    backgroundColor: '#242424',
  },
  softSampleFogLineOne: {
    left: 4,
    top: 2,
    width: 96,
    transform: [{ rotate: '-4deg' }],
  },
  softSampleFogLineTwo: {
    left: 0,
    top: 32,
    width: 102,
    opacity: 0.86,
    transform: [{ rotate: '-5deg' }],
  },
  softSampleFogLineThree: {
    left: 7,
    top: 63,
    width: 88,
    opacity: 0.86,
    transform: [{ rotate: '5deg' }],
  },
  weatherArtIcon: {
    width: 170,
    height: 170,
  },
  sunHalo: {
    position: 'absolute',
    width: 142,
    height: 142,
    borderRadius: 71,
    borderWidth: 3,
    borderStyle: 'dashed',
    opacity: 0.5,
  },
  sunCore: {
    width: 102,
    height: 102,
    borderRadius: 51,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(24,28,24,0.22)',
    shadowOffset: { width: 8, height: 16 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
  },
  cloudBase: {
    position: 'absolute',
    top: 64,
    right: 18,
    width: 138,
    height: 76,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(24,28,24,0.24)',
    shadowOffset: { width: 12, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 26,
  },
  cloudPuffLarge: {
    position: 'absolute',
    top: 32,
    right: 78,
    width: 82,
    height: 82,
    borderRadius: 41,
  },
  cloudPuffSmall: {
    position: 'absolute',
    top: 76,
    right: 0,
    width: 62,
    height: 62,
    borderRadius: 31,
  },
  weatherDrops: {
    position: 'absolute',
    top: 128,
    right: 24,
    width: 128,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    transform: [{ rotate: '-14deg' }],
  },
  rainDrop: {
    width: 10,
    height: 42,
    borderRadius: 7,
    opacity: 0.96,
  },
  rainDropMiddle: {
    marginTop: 10,
  },
  rainDropFast: {
    marginTop: -8,
    height: 52,
  },
  rainDropWide: {
    marginTop: 14,
    height: 36,
  },
  thunderFlash: {
    position: 'absolute',
    top: 28,
    right: 4,
    width: 150,
    height: 132,
    borderRadius: 48,
    backgroundColor: 'rgba(255,232,87,0.36)',
  },
  thunderBolt: {
    position: 'absolute',
    top: 90,
    right: 62,
    width: 62,
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '11deg' }],
  },
  thunderBoltTop: {
    position: 'absolute',
    top: 4,
    left: 20,
    width: 24,
    height: 60,
    borderRadius: 10,
    transform: [{ rotate: '28deg' }],
  },
  thunderBoltBottom: {
    position: 'absolute',
    top: 38,
    left: 7,
    width: 24,
    height: 58,
    borderRadius: 10,
    transform: [{ rotate: '28deg' }],
  },
  snowDots: {
    position: 'absolute',
    top: 124,
    right: 10,
    width: 142,
    height: 54,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  snowDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#72b8d8',
    opacity: 0.98,
    shadowColor: 'rgba(9,70,102,0.32)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.34,
    shadowRadius: 8,
  },
  snowDotMiddle: {
    width: 23,
    height: 23,
    borderRadius: 12,
    marginTop: 16,
  },
  snowDotSmall: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderWidth: 2,
  },
  snowDotLow: {
    marginTop: 20,
  },
  fogLines: {
    position: 'absolute',
    top: 126,
    right: 12,
    width: 136,
    gap: 14,
  },
  fogLinesCloudy: {
    top: 138,
    opacity: 0.68,
  },
  fogLine: {
    height: 7,
    borderRadius: 5,
    opacity: 0.86,
  },
  fogLineShort: {
    width: 96,
    marginLeft: 28,
  },
  decisionMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
  },
  decisionMetaChipPrimary: {
    minHeight: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  decisionMetaChipPrimaryText: {
    fontSize: 11,
    fontWeight: '900',
  },
  decisionMetaChip: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
    backgroundColor: 'rgba(214,210,196,0.58)',
  },
  decisionMetaChipText: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '900',
  },
  decisionMain: {
    marginTop: 242,
    maxWidth: 260,
  },
  heroSummary: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
    marginTop: 2,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  decisionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  decisionLabel: {
    color: 'rgba(36,36,36,0.54)',
    fontSize: 12,
    fontWeight: '900',
  },
  decisionCondition: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  decisionTitle: {
    color: '#242424',
    fontSize: 27,
    lineHeight: 31,
    fontWeight: '900',
    flexShrink: 1,
  },
  decisionSummary: {
    color: 'rgba(36,36,36,0.68)',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 9,
  },
  decisionBottomRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  tempRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    alignSelf: 'flex-start',
    justifyContent: 'flex-start',
    minWidth: 128,
    marginTop: 0,
    flexShrink: 0,
  },
  temperature: {
    color: '#242424',
    fontSize: 86,
    lineHeight: 86,
    fontWeight: '900',
  },
  degree: {
    color: '#242424',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 17,
    marginLeft: 2,
  },
  centerAnswer: {
    position: 'absolute',
    top: 52,
    left: '50%',
    marginLeft: -66,
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: '#f8f8f2',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: 'rgba(54,56,48,0.16)',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
  },
  centerAnswerTitle: {
    color: '#192333',
    fontSize: 28,
    lineHeight: 29,
    fontWeight: '900',
    marginTop: 3,
  },
  centerAnswerCaption: {
    color: 'rgba(25,35,51,0.64)',
    fontSize: 11,
    fontWeight: '900',
  },
  condition: {
    color: '#242424',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 15,
    marginLeft: 14,
  },
  signalGrid: {
    position: 'relative',
    zIndex: 3,
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  signalItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: 'rgba(205,201,187,0.68)',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 11,
    paddingVertical: 9,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 3,
  },
  signalLabel: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 10,
    fontWeight: '900',
  },
  signalValue: {
    color: '#242424',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
    flexShrink: 1,
  },
  sectionTitle: {
    marginTop: 16,
    marginBottom: 10,
  },
  sectionHeading: {
    color: '#242424',
    fontSize: 18,
    fontWeight: '900',
  },
  sectionCaption: {
    color: '#696e65',
    marginTop: 5,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  sourceGrid: {
    gap: 9,
  },
  mockSection: {
    marginTop: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(205,201,187,0.66)',
    padding: 16,
  },
  mockSectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  mockSectionTitle: {
    color: '#242424',
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
  },
  mockSectionButton: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(244,245,242,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  mockSectionButtonText: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  reasonSummary: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(205,201,187,0.68)',
    padding: 13,
    marginBottom: 10,
  },
  reasonSummaryTitle: {
    color: '#242424',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  reasonSummaryText: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 5,
  },
  evidenceRow: {
    minHeight: 64,
    borderRadius: 17,
    backgroundColor: 'rgba(205,201,187,0.68)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  evidenceContent: {
    flex: 1,
    minWidth: 0,
  },
  evidenceName: {
    color: '#242424',
    fontSize: 14,
    fontWeight: '900',
  },
  evidenceSub: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  sourceWeatherPillCompact: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(244,245,242,0.58)',
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  miniWeatherDrawing: {
    width: 44,
    height: 44,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniWeatherIconImage: {
    width: 44,
    height: 44,
  },
  compareSummaryWeatherSvg: {
    width: 34,
    height: 34,
  },
  compareForecastWeatherSvg: {
    width: 24,
    height: 24,
  },
  miniSunHalo: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderStyle: 'dashed',
    opacity: 0.78,
  },
  miniSunCore: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  miniCloudBase: {
    position: 'absolute',
    left: 4,
    top: 16,
    width: 34,
    height: 20,
    borderRadius: 14,
  },
  miniCloudPuff: {
    position: 'absolute',
    left: 10,
    top: 7,
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  miniCloudSmall: {
    position: 'absolute',
    right: 3,
    top: 17,
    width: 15,
    height: 15,
    borderRadius: 8,
  },
  miniRainDrops: {
    position: 'absolute',
    left: 12,
    top: 34,
    width: 22,
    height: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    transform: [{ rotate: '-14deg' }],
  },
  miniRainDrop: {
    width: 5,
    height: 14,
    borderRadius: 3,
  },
  miniRainDropLower: {
    marginTop: 3,
  },
  miniSnowDots: {
    position: 'absolute',
    left: 10,
    top: 34,
    width: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  miniSnowDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#f1ece1',
  },
  miniThunder: {
    position: 'absolute',
    left: 15,
    top: 23,
    width: 19,
    height: 28,
  },
  miniThunderTop: {
    position: 'absolute',
    top: 0,
    left: 5,
    width: 5,
    height: 13,
    borderRadius: 2,
    backgroundColor: '#ffd33d',
    transform: [{ rotate: '28deg' }],
  },
  miniThunderBottom: {
    position: 'absolute',
    top: 8,
    left: 1,
    width: 5,
    height: 13,
    borderRadius: 2,
    backgroundColor: '#ffd33d',
    transform: [{ rotate: '28deg' }],
  },
  miniFogLines: {
    position: 'absolute',
    left: 2,
    top: 26,
    width: 29,
    gap: 5,
  },
  miniFogLine: {
    height: 2,
    borderRadius: 2,
  },
  miniFogLineShort: {
    width: 16,
    height: 2,
    borderRadius: 2,
    marginLeft: 5,
  },
  sourceTempCompact: {
    color: '#242424',
    fontSize: 13,
    fontWeight: '900',
  },
  liveEvidenceBadge: {
    minHeight: 29,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(214,210,196,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
    maxWidth: 108,
  },
  liveEvidenceBadgeText: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  sourceForecastCard: {
    borderRadius: 22,
    backgroundColor: '#f3f4f1',
    padding: 14,
    gap: 13,
  },
  sourceForecastHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sourceForecastTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  sourceLogoFrame: {
    width: 44,
    height: 44,
    borderRadius: 20,
    backgroundColor: '#f1ece1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
    overflow: 'hidden',
  },
  sourceLogoBehind: {
    position: 'absolute',
    color: '#2f1822',
    fontSize: 12,
    fontWeight: '900',
  },
  sourceLogoImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  sourceLogoFallback: {
    width: 44,
    height: 44,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceLogoFallbackText: {
    color: '#f1ece1',
    fontSize: 13,
    fontWeight: '900',
  },
  sourceForecastMain: {
    minHeight: 76,
    borderRadius: 18,
    backgroundColor: '#eef0ed',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
  },
  sourceWeatherIcon: {
    width: 48,
    height: 48,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceWeatherIconText: {
    color: '#f1ece1',
    fontSize: 15,
    fontWeight: '900',
  },
  sourceForecastReading: {
    flex: 1,
    minWidth: 0,
  },
  sourceTempLarge: {
    color: '#2f1822',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  sourceConditionLarge: {
    color: '#62665f',
    fontSize: 13,
    fontWeight: '900',
    marginTop: 3,
  },
  reasonCard: {
    borderRadius: 22,
    backgroundColor: '#242424',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 17,
    marginBottom: 10,
  },
  reasonKicker: {
    color: 'rgba(238,233,221,0.62)',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  reasonText: {
    color: '#eee9dd',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '800',
  },
  reasonSignalList: {
    gap: 8,
    marginTop: 14,
  },
  reasonSignalItem: {
    borderRadius: 14,
    backgroundColor: 'rgba(244,245,242,0.12)',
    padding: 11,
  },
  reasonSignalLabel: {
    color: 'rgba(238,233,221,0.62)',
    fontSize: 11,
    fontWeight: '900',
  },
  reasonSignalValue: {
    color: '#eee9dd',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  sourceCard: {
    borderRadius: 20,
    backgroundColor: '#f4f5f2',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sourceMark: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceMarkText: {
    color: '#f1ece1',
    fontSize: 13,
    fontWeight: '900',
  },
  sourceContent: {
    flex: 1,
    minWidth: 0,
  },
  sourceName: {
    color: '#2f1822',
    fontSize: 14,
    fontWeight: '900',
  },
  sourceDetail: {
    color: '#2a2a2a',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 4,
  },
  sourceWeatherPill: {
    minWidth: 62,
    borderRadius: 16,
    backgroundColor: '#eef0ed',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  sourceTemp: {
    color: '#2f1822',
    fontSize: 16,
    fontWeight: '900',
  },
  sourceCondition: {
    color: '#62665f',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  forecastPanel: {
    borderRadius: 18,
    backgroundColor: 'rgba(214,210,196,0.68)',
    overflow: 'hidden',
  },
  forecastLead: {
    padding: 13,
    backgroundColor: 'rgba(214,210,196,0.62)',
  },
  forecastLeadLabel: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 5,
  },
  forecastLeadText: {
    color: '#242424',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
  },
  forecastHint: {
    borderRadius: 15,
    backgroundColor: 'rgba(214,210,196,0.62)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 11,
    marginTop: 10,
  },
  forecastHintLabel: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '900',
  },
  forecastHintText: {
    color: '#242424',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  forecastRows: {
    padding: 10,
    gap: 9,
  },
  forecastRow: {
    minHeight: 66,
    borderRadius: 17,
    backgroundColor: 'rgba(214,210,196,0.62)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
  },
  forecastMark: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forecastMarkText: {
    fontSize: 14,
    fontWeight: '900',
  },
  forecastWeatherIconFrame: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(214,210,196,0.70)',
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  forecastMain: {
    flex: 1,
    minWidth: 0,
  },
  forecastTime: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    fontWeight: '800',
  },
  forecastTitle: {
    color: '#242424',
    fontSize: 15,
    fontWeight: '900',
    marginTop: 3,
  },
  forecastSide: {
    alignItems: 'flex-end',
  },
  forecastTemp: {
    color: '#242424',
    fontSize: 15,
    fontWeight: '900',
  },
  forecastNote: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
  },
  reportBox: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 0,
    paddingLeft: 15,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    minHeight: 48,
  },
  localReportCard: {
    marginTop: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(214,210,196,0.66)',
    padding: 14,
    gap: 10,
  },
  localReportHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  localReportTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  localReportTitleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: 7,
  },
  localReportTitle: {
    color: '#242424',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    flexShrink: 1,
  },
  localReportPlace: {
    color: 'rgba(36,36,36,0.50)',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '900',
  },
  localReportCaption: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    marginTop: 4,
  },
  localOptions: {
    gap: 7,
  },
  localOptionChip: {
    minHeight: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'rgba(214,210,196,0.66)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  localOptionChipActive: {
    borderColor: 'transparent',
    backgroundColor: '#242424',
  },
  localOptionText: {
    color: '#242424',
    fontSize: 13,
    fontWeight: '900',
  },
  localOptionTextActive: {
    color: '#f4f5f2',
  },
  localReportStatus: {
    minHeight: 16,
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 8,
  },
  reportInput: {
    flex: 1,
    color: '#242424',
    fontSize: 16,
    fontWeight: '800',
    minHeight: 42,
  },
  primaryButton: {
    borderRadius: 15,
    backgroundColor: '#242424',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: '#f4f5f2',
    fontSize: 12,
    fontWeight: '900',
  },
  reportList: {
    marginTop: 10,
    gap: 9,
  },
  reportItem: {
    borderRadius: 17,
    backgroundColor: 'rgba(214,210,196,0.68)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reportContent: {
    flex: 1,
    minWidth: 0,
  },
  reportMeta: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 5,
  },
  reportBody: {
    color: '#242424',
    fontSize: 13,
    fontWeight: '900',
    flexShrink: 1,
  },
  reportCondition: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  reportSide: {
    alignItems: 'flex-end',
    gap: 7,
  },
  reportIssueButton: {
    minHeight: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(36,36,36,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  reportIssueButtonPending: {
    backgroundColor: 'rgba(127,159,141,0.22)',
  },
  reportIssueText: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 10,
    fontWeight: '900',
  },
  emptyState: {
    marginTop: 12,
    borderRadius: 22,
    backgroundColor: '#242424',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  emptyStateMark: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: '#f3f4f1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateMarkText: {
    color: '#2a2a2a',
    fontSize: 20,
    fontWeight: '900',
  },
  emptyStateContent: {
    flex: 1,
    minWidth: 0,
  },
  emptyStateTitle: {
    color: '#eee9dd',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
  },
  emptyStateBody: {
    color: '#696e65',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: 5,
  },
  emptyStateAction: {
    color: '#242424',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
    marginTop: 9,
  },
  mapCard: {
    height: 470,
    borderRadius: 30,
    backgroundColor: '#d7d5cb',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 16,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    position: 'relative',
  },
  mapControlCard: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    padding: 14,
    marginBottom: 12,
  },
  mapControlTitle: {
    color: '#242424',
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
  },
  mapControlCaption: {
    color: '#696e65',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  mapControlRow: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 10,
  },
  mapControlChip: {
    flex: 1,
    minHeight: 36,
    borderRadius: 15,
    backgroundColor: '#eef0ed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapControlChipActive: {
    backgroundColor: '#242424',
  },
  mapControlChipText: {
    color: 'rgba(36,36,36,0.62)',
    fontSize: 12,
    fontWeight: '900',
  },
  mapControlChipTextActive: {
    color: '#f4f5f2',
  },
  mapFilterChip: {
    flex: 1,
    minHeight: 32,
    borderRadius: 14,
    backgroundColor: 'rgba(214,210,196,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapFilterChipActive: {
    backgroundColor: '#b9dde5',
  },
  mapFilterChipText: {
    color: 'rgba(36,36,36,0.62)',
    fontSize: 11,
    fontWeight: '900',
  },
  mapFilterChipTextActive: {
    color: '#242424',
  },
  mapTileLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#d7d5cb',
  },
  mapNativeFallback: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#cfd7d8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapNativeFallbackText: {
    position: 'absolute',
    top: 18,
    left: 18,
    color: 'rgba(36,36,36,0.52)',
    fontSize: 12,
    fontWeight: '900',
  },
  mapNativeBlockOne: {
    position: 'absolute',
    top: 62,
    left: 28,
    width: 118,
    height: 92,
    borderRadius: 24,
    backgroundColor: 'rgba(244,245,242,0.72)',
    transform: [{ rotate: '-7deg' }],
  },
  mapNativeBlockTwo: {
    position: 'absolute',
    top: 80,
    right: 32,
    width: 92,
    height: 132,
    borderRadius: 28,
    backgroundColor: 'rgba(190,204,184,0.62)',
    transform: [{ rotate: '12deg' }],
  },
  mapNativeBlockThree: {
    position: 'absolute',
    bottom: 118,
    left: 76,
    width: 150,
    height: 94,
    borderRadius: 30,
    backgroundColor: 'rgba(112,153,174,0.35)',
    transform: [{ rotate: '8deg' }],
  },
  mapNativeLaneOne: {
    position: 'absolute',
    left: -18,
    top: 146,
    width: 420,
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.88)',
    transform: [{ rotate: '25deg' }],
  },
  mapNativeLaneTwo: {
    position: 'absolute',
    left: 72,
    top: 40,
    width: 300,
    height: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.74)',
    transform: [{ rotate: '-54deg' }],
  },
  mapNativeLaneThree: {
    position: 'absolute',
    left: -42,
    bottom: 144,
    width: 360,
    height: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.72)',
    transform: [{ rotate: '-26deg' }],
  },
  mapNativeWater: {
    position: 'absolute',
    right: -44,
    bottom: 34,
    width: 180,
    height: 100,
    borderRadius: 60,
    backgroundColor: 'rgba(75,141,174,0.34)',
    transform: [{ rotate: '-18deg' }],
  },
  mapScrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(244,245,242,0.30)',
  },
  mapGlowZoneOne: {
    position: 'absolute',
    left: 32,
    top: 164,
    width: 124,
    height: 82,
    borderRadius: 46,
    backgroundColor: 'rgba(145,178,190,0.28)',
    opacity: 0.82,
    transform: [{ rotate: '-8deg' }],
  },
  mapGlowZoneTwo: {
    position: 'absolute',
    right: 30,
    top: 82,
    width: 104,
    height: 122,
    borderRadius: 54,
    backgroundColor: 'rgba(244,245,242,0.46)',
    opacity: 0.9,
    transform: [{ rotate: '12deg' }],
  },
  mapRoadOne: {
    position: 'absolute',
    left: 24,
    top: 126,
    width: 330,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(244,245,242,0.72)',
    transform: [{ rotate: '22deg' }],
  },
  mapRoadTwo: {
    position: 'absolute',
    left: 88,
    top: 82,
    width: 250,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(244,245,242,0.64)',
    transform: [{ rotate: '-52deg' }],
  },
  mapRoadThree: {
    position: 'absolute',
    left: 15,
    top: 332,
    width: 310,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(244,245,242,0.60)',
    transform: [{ rotate: '-38deg' }],
  },
  mapPin: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#d6d2c4',
    borderWidth: 4,
    borderColor: 'transparent',
  },
  mapPinOne: {
    top: 80,
    left: 70,
  },
  mapPinTwo: {
    top: 150,
    right: 82,
    backgroundColor: '#dcd8cb',
  },
  mapPinThree: {
    bottom: 126,
    left: 148,
    backgroundColor: '#ffeb4a',
  },
  mapTitle: {
    color: '#242424',
    fontSize: 24,
    lineHeight: 27,
    fontWeight: '900',
    marginTop: 10,
  },
  mapCaption: {
    color: 'rgba(36,36,36,0.58)',
    marginTop: 7,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  mapOverlay: {
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 16,
  },
  mapOverlayTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mapRadiusChip: {
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: '#242424',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  mapRadiusChipText: {
    color: '#f4f5f2',
    fontSize: 11,
    fontWeight: '900',
  },
  mapOverlayCount: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  mapKicker: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  mapReportMarker: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(70,74,66,0.13)',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.26,
    shadowRadius: 28,
  },
  mapReportMarkerActive: {
    transform: [{ scale: 1.08 }],
    borderWidth: 4,
    borderColor: '#f4f5f2',
  },
  mapReportMarkerText: {
    color: '#242424',
    fontSize: 16,
    fontWeight: '900',
  },
  mapCurrentLocation: {
    position: 'absolute',
    top: '46%',
    left: '50%',
    width: 38,
    height: 38,
    borderRadius: 19,
    marginLeft: -19,
    marginTop: -19,
    backgroundColor: 'rgba(36,36,36,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  mapCurrentDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#242424',
    borderWidth: 3,
    borderColor: '#f4f5f2',
  },
  mapStats: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  mapStatItem: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#f3f4f1',
    padding: 13,
  },
  mapStatValue: {
    color: '#2f1822',
    fontSize: 18,
    fontWeight: '900',
  },
  mapStatLabel: {
    color: '#757a72',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 4,
  },
  mapSelectedCard: {
    marginTop: 12,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapSelectedKicker: {
    color: 'rgba(36,36,36,0.50)',
    fontSize: 12,
    fontWeight: '900',
  },
  mapSelectedPlace: {
    color: '#242424',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 5,
  },
  mapSelectedBody: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    marginTop: 7,
    maxWidth: 230,
  },
  mapSelectedCondition: {
    color: '#242424',
    fontSize: 13,
    fontWeight: '900',
  },
  mapSelectedSide: {
    alignItems: 'flex-end',
    gap: 8,
  },
  mapListHeader: {
    marginTop: 18,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mapListTitle: {
    color: '#242424',
    fontSize: 18,
    fontWeight: '900',
  },
  mapListAction: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  mapReportItem: {
    borderRadius: 18,
    backgroundColor: 'rgba(214,210,196,0.58)',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapReportItemActive: {
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: '#ffffff',
  },
  mapReportContent: {
    flex: 1,
    minWidth: 0,
  },
  reportHeaderBlock: {
    marginBottom: 18,
  },
  reportHeaderTitle: {
    color: '#242424',
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
  },
  reportHeaderCaption: {
    color: 'rgba(36,36,36,0.52)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    marginTop: 5,
  },
  reportTabbedCard: {
    marginBottom: 18,
  },
  reportTabRail: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 0,
    gap: 5,
  },
  reportTopTab: {
    flex: 1,
    minHeight: 50,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  reportTopTabActive: {
    minHeight: 56,
  },
  reportTopTabText: {
    color: 'rgba(36,36,36,0.62)',
    fontSize: 14,
    fontWeight: '900',
  },
  reportTabPanel: {
    marginTop: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    padding: 20,
    minHeight: 468,
    overflow: 'hidden',
  },
  reportPanelTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
  },
  reportPanelCaption: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    marginTop: 8,
    marginBottom: 18,
  },
  reportBigQuestionBox: {
    minHeight: 92,
    borderRadius: 20,
    backgroundColor: '#fffaf4',
    paddingLeft: 14,
    paddingRight: 70,
    paddingVertical: 14,
    justifyContent: 'center',
    position: 'relative',
  },
  reportBigQuestionInput: {
    flex: 1,
    minHeight: 54,
    color: '#242424',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '900',
    paddingVertical: 0,
  },
  reportRoundSubmit: {
    position: 'absolute',
    right: 14,
    top: 23,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#242424',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportRoundSubmitText: {
    color: '#f4f5f2',
    fontSize: 24,
    lineHeight: 26,
    fontWeight: '900',
  },
  reportInlineNotice: {
    marginTop: 12,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  reportPanelSectionHeader: {
    marginTop: 26,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportPanelSectionTitle: {
    fontSize: 20,
    fontWeight: '900',
  },
  reportPanelSectionMeta: {
    fontSize: 12,
    fontWeight: '900',
  },
  reportFilterPill: {
    alignSelf: 'flex-start',
    minHeight: 42,
    borderRadius: 18,
    backgroundColor: '#242424',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginBottom: 18,
  },
  reportFilterPillText: {
    color: '#f4f5f2',
    fontSize: 13,
    fontWeight: '900',
  },
  reportModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  reportModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 26,
    backgroundColor: '#f4f1e9',
    padding: 18,
  },
  reportModalClose: {
    marginTop: 10,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportModalCloseText: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 13,
    fontWeight: '900',
  },
  reportAnswerBubble: {
    marginTop: 14,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 14,
  },
  reportAnswerText: {
    color: '#3b3d38',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
  },
  requestCard: {
    borderRadius: 28,
    backgroundColor: '#b9dde5',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 16,
    marginBottom: 14,
    overflow: 'hidden',
  },
  requestKicker: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderRadius: 15,
    backgroundColor: '#242424',
    color: '#f4f5f2',
    fontSize: 12,
    fontWeight: '900',
    paddingHorizontal: 11,
    paddingTop: 7,
  },
  requestTitle: {
    color: '#242424',
    fontSize: 23,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: 12,
    marginBottom: 12,
  },
  reportFeedMode: {
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.48)',
    padding: 5,
    flexDirection: 'row',
    gap: 5,
    marginBottom: 13,
  },
  reportFeedModeButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportFeedModeButtonActive: {
    backgroundColor: '#242424',
  },
  reportFeedModeText: {
    color: 'rgba(36,36,36,0.62)',
    fontSize: 13,
    fontWeight: '900',
  },
  reportFeedModeTextActive: {
    color: '#f4f5f2',
  },
  reportGuide: {
    flexDirection: 'row',
    gap: 7,
    marginBottom: 12,
  },
  reportStep: {
    flex: 1,
    minHeight: 72,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 10,
  },
  reportStepLabel: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  reportStepText: {
    color: '#242424',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  requestForm: {
    gap: 9,
    alignItems: 'stretch',
    borderRadius: 23,
    backgroundColor: '#ffffff',
    padding: 9,
  },
  requestInput: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    color: '#242424',
    minHeight: 52,
    paddingHorizontal: 13,
    fontSize: 16,
    fontWeight: '900',
    width: '100%',
  },
  requestSubmitButton: {
    borderRadius: 18,
    backgroundColor: '#242424',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  requestSubmitText: {
    color: '#f4f5f2',
    fontSize: 12,
    fontWeight: '900',
  },
  reportSectionHeader: {
    marginTop: 20,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportSectionTitle: {
    color: '#242424',
    fontSize: 20,
    fontWeight: '900',
  },
  reportSectionAction: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  requestList: {
    gap: 10,
  },
  requestListItem: {
    borderRadius: 15,
    backgroundColor: 'rgba(214,210,196,0.58)',
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  requestListItemActive: {
    backgroundColor: '#ffffff',
    borderColor: 'transparent',
  },
  requestMark: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  requestMarkText: {
    color: '#242424',
    fontSize: 14,
    fontWeight: '900',
  },
  requestMarkTextActive: {
    color: '#f4f5f2',
  },
  requestListContent: {
    flex: 1,
    minWidth: 0,
  },
  requestQuestion: {
    color: '#242424',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  requestQuestionActive: {
    color: '#242424',
  },
  requestHint: {
    color: '#696e65',
    marginTop: 3,
    fontSize: 12,
    lineHeight: 15,
  },
  requestHintActive: {
    color: 'rgba(36,36,36,0.60)',
  },
  requestStatus: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  requestStatusActive: {
    color: '#242424',
  },
  replyBox: {
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(214,210,196,0.62)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
  },
  replyEyebrow: {
    color: '#242424',
    fontSize: 12,
    fontWeight: '900',
  },
  replyQuestion: {
    color: '#242424',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
    marginTop: 7,
  },
  replyInput: {
    marginTop: 12,
    minHeight: 96,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    color: '#242424',
    fontSize: 16,
    lineHeight: 22,
    padding: 14,
    textAlignVertical: 'top',
  },
  replySubmitButton: {
    marginTop: 12,
    minHeight: 42,
    borderRadius: 15,
    backgroundColor: '#242424',
    alignItems: 'center',
    justifyContent: 'center',
  },
  replySubmitText: {
    color: '#f4f5f2',
    fontSize: 12,
    fontWeight: '900',
  },
  replyNotice: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 10,
  },
  liveReportList: {
    gap: 10,
  },
  liveReportItem: {
    minHeight: 74,
    borderRadius: 17,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  liveReportMark: {
    width: 50,
    height: 50,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveReportMarkText: {
    fontSize: 15,
    fontWeight: '900',
  },
  liveReportMain: {
    flex: 1,
    minWidth: 0,
  },
  liveReportTopRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveReportPlace: {
    color: '#242424',
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
  },
  liveReportTime: {
    color: 'rgba(36,36,36,0.46)',
    fontSize: 11,
    fontWeight: '900',
  },
  liveReportBody: {
    color: '#3b3d38',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 3,
  },
  liveReportBottomRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  liveReportCondition: {
    minHeight: 22,
    borderRadius: 11,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingTop: 4,
    fontSize: 11,
    fontWeight: '900',
  },
  liveReportSource: {
    color: 'rgba(36,36,36,0.44)',
    fontSize: 11,
    fontWeight: '900',
  },
  liveReportAction: {
    alignItems: 'flex-end',
    paddingTop: 2,
  },
  compareHero: {
    borderRadius: 28,
    backgroundColor: 'rgba(214,210,196,0.62)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 17,
    marginBottom: 14,
  },
  compareKicker: {
    alignSelf: 'flex-start',
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: '#242424',
    color: '#f4f5f2',
    fontSize: 12,
    fontWeight: '900',
    paddingHorizontal: 10,
    paddingTop: 6,
  },
  compareTitle: {
    color: '#242424',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: 10,
    marginBottom: 16,
  },
  compareContextBar: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
    marginBottom: 14,
  },
  compareContextLabel: {
    color: 'rgba(36,36,36,0.52)',
    fontSize: 11,
    fontWeight: '900',
  },
  compareContextText: {
    color: '#242424',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  compareSummaryList: {
    gap: 10,
  },
  compareSummaryCard: {
    minHeight: 70,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  compareServiceMark: {
    width: 42,
    height: 42,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareServiceMarkText: {
    color: '#f1ece1',
    fontSize: 13,
    fontWeight: '900',
  },
  compareServiceLogoFrame: {
    width: 48,
    height: 48,
    borderRadius: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  compareServiceLogoImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  compareServiceLogoSvg: {
    width: 44,
    height: 44,
  },
  compareSummaryContent: {
    flex: 1,
    minWidth: 0,
  },
  compareSummaryName: {
    color: '#242424',
    fontSize: 14,
    fontWeight: '900',
  },
  compareSummaryText: {
    color: '#696e65',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  compareSummaryValue: {
    minWidth: 50,
    maxWidth: 62,
    borderRadius: 15,
    backgroundColor: 'rgba(244,245,242,0.56)',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 7,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  compareSummaryValueText: {
    color: '#242424',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareSummaryWeatherBadge: {
    width: 74,
    minHeight: 72,
    borderRadius: 17,
    backgroundColor: 'rgba(214,210,196,0.46)',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 7,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareSummaryWeatherIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  compareSummaryWeatherText: {
    color: '#242424',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareSummarySub: {
    color: 'rgba(36,36,36,0.50)',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 2,
    textAlign: 'center',
  },
  compareMode: {
    borderRadius: 20,
    backgroundColor: '#242424',
    padding: 5,
    flexDirection: 'row',
    marginBottom: 14,
  },
  compareModeButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareModeButtonActive: {
    backgroundColor: '#f4f5f2',
  },
  compareModeText: {
    color: '#d8c9d0',
    fontSize: 14,
    fontWeight: '900',
  },
  compareModeTextActive: {
    color: '#242424',
  },
  comparePanel: {
    borderRadius: 24,
    backgroundColor: 'rgba(214,210,196,0.62)',
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
  },
  comparePanelTitle: {
    paddingHorizontal: 4,
    paddingVertical: 6,
    marginBottom: 8,
  },
  comparePanelHeading: {
    color: '#242424',
    fontSize: 20,
    fontWeight: '900',
  },
  comparePanelCaption: {
    color: '#696e65',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  compareRows: {
    gap: 10,
  },
  compareTableFrame: {
    minHeight: 254,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  compareTableServiceColumn: {
    width: 66,
    borderRightWidth: 1,
    borderRightColor: 'transparent',
    backgroundColor: 'rgba(214,210,196,0.46)',
  },
  compareTableCorner: {
    height: 40,
    paddingHorizontal: 6,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
  },
  compareTableCornerText: {
    color: '#242424',
    fontSize: 10,
    fontWeight: '900',
  },
  compareTableServiceCell: {
    height: 62,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
  },
  compareTableServiceIconFrame: {
    width: 24,
    height: 24,
    borderRadius: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 2,
  },
  compareTableServiceIconFallback: {
    width: 24,
    height: 24,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  compareTableServiceIcon: {
    width: 28,
    height: 28,
    marginBottom: 3,
  },
  compareTableServiceText: {
    color: '#242424',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareTableScrollContent: {
    paddingRight: 8,
  },
  compareForecastColumn: {
    width: 48,
    borderRightWidth: 1,
    borderRightColor: 'transparent',
  },
  compareForecastColumnDaily: {
    width: 82,
  },
  compareForecastColumnHead: {
    height: 40,
    paddingHorizontal: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(214,210,196,0.42)',
  },
  compareForecastColumnLabel: {
    color: '#242424',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareForecastCell: {
    height: 62,
    paddingHorizontal: 3,
    paddingVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(214,210,196,0.34)',
  },
  compareForecastCellDaily: {
    paddingHorizontal: 5,
  },
  compareForecastIconFrame: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  compareForecastMarkText: {
    color: '#f1ece1',
    fontSize: 12,
    fontWeight: '900',
  },
  compareForecastTextBox: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
  },
  compareForecastWeather: {
    color: '#242424',
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareForecastDetail: {
    color: '#696e65',
    fontSize: 7,
    lineHeight: 9,
    fontWeight: '800',
    marginTop: 1,
    textAlign: 'center',
  },
  compareDailyPeriods: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 2,
  },
  compareDailyPeriod: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
  },
  compareDailyPeriodLabel: {
    color: '#8a8d86',
    fontSize: 7,
    lineHeight: 8,
    fontWeight: '900',
    marginBottom: 1,
  },
  compareDailyPeriodDetail: {
    color: '#242424',
    fontSize: 7,
    lineHeight: 8,
    fontWeight: '900',
    marginTop: 1,
    textAlign: 'center',
  },
  compareDifferenceList: {
    gap: 10,
  },
  compareInsightCard: {
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 15,
    marginBottom: 12,
  },
  compareInsightLabel: {
    color: '#757a72',
    fontSize: 12,
    fontWeight: '900',
  },
  compareInsightText: {
    color: '#242424',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    marginTop: 6,
  },
  compareDifferenceItem: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  compareDifferenceLogo: {
    width: 44,
    height: 44,
  },
  compareDifferenceContent: {
    flex: 1,
    minWidth: 0,
  },
  compareDifferenceName: {
    color: '#242424',
    fontSize: 14,
    fontWeight: '900',
  },
  compareDifferenceBody: {
    color: 'rgba(36,36,36,0.60)',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginTop: 4,
  },
  compareDifferenceBadge: {
    color: '#242424',
    fontSize: 11,
    fontWeight: '900',
  },
  providerAttributionCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(214,210,196,0.58)',
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginTop: 12,
    gap: 5,
  },
  providerAttributionLabel: {
    color: 'rgba(36,36,36,0.58)',
    fontSize: 11,
    fontWeight: '900',
  },
  providerAttributionText: {
    color: '#242424',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  compareTable: {
    borderRadius: 22,
    backgroundColor: '#f3f4f1',
    overflow: 'hidden',
  },
  compareRow: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  compareTime: {
    color: '#2f1822',
    width: 42,
    fontSize: 13,
    fontWeight: '900',
  },
  compareCell: {
    color: '#2a2a2a',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  bottomTabs: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 48,
    borderRadius: 24,
    backgroundColor: '#f3f4f1',
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 7,
    shadowColor: 'rgba(36,36,36,0.16)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 14,
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  tabButtonActive: {
    backgroundColor: '#242424',
  },
  tabText: {
    color: '#62665f',
    fontSize: 11,
    fontWeight: '900',
  },
  tabTextActive: {
    color: '#eee9dd',
  },
  tabIconVector: {
    width: 30,
    height: 30,
    marginBottom: 0,
  },
});






